---
services:
  alist:
    container_name: alist
    image: 'sync/alist:latest'
    volumes:
      - '../data/alist/data:/opt/alist/data'
      # - ./aria2.conf:/root/.aria2/aria2.conf
    # ports:
    #   - '5244:5244'
    #   - '6800:6800'
    environment:
      - PUID=1000
      - PGID=996
      - UMASK=022
      - TZ=UTC
    restart: unless-stopped
    networks:
      im-net:
        ipv4_address: 10.1.1.6
    extra_hosts:
      - "host.docker.internal:host-gateway"
networks:
  im-net:
    external: true